"""Orchestrator JSON config assembly."""

import json
import sys


def build_config(
    nodes: list[dict],
    links: list[dict],
    sim_params: dict | None = None,
    radio_params: dict | None = None,
    source_description: str = "",
) -> dict:
    """Assemble orchestrator config JSON.

    nodes: list of {name, role, lat, lon}
    links: list of {from, to, snr, rssi, bidir, snr_std_dev, loss?}
    """
    if sim_params is None:
        sim_params = {}
    if radio_params is None:
        radio_params = {}

    config = {
        "_source": source_description or "Generated by topology_generator (ITM)",
        "simulation": {
            "duration_ms": sim_params.get("duration_ms", 300000),
            "step_ms": sim_params.get("step_ms", 5),
            "warmup_ms": sim_params.get("warmup_ms", 5000),
            "hot_start": sim_params.get("hot_start", True),
        },
        "nodes": list(nodes),
        "topology": {
            "links": list(links),
        },
        "commands": [],
    }

    if radio_params:
        config["simulation"]["radio"] = {
            "sf": radio_params.get("sf", 8),
            "bw": radio_params.get("bw", 62500),
            "cr": radio_params.get("cr", 4),
        }

    return config


def emit_config(config: dict, output_path: str | None = None):
    """Write config to file or stdout."""
    output_str = json.dumps(config, indent=2)
    if output_path:
        with open(output_path, "w") as f:
            f.write(output_str + "\n")
        print(f"Written to {output_path}", file=sys.stderr)
    else:
        print(output_str)
