#!/usr/bin/env bash
# Focused rx_delay sweep — verifies whether rx_delay has any effect on delivery.
#
# Holds the winning tx/dtx configuration fixed and varies rx_base across a
# reasonable range. Reuses topology files already generated by run_sweep.sh.
#
# Usage:
#   ./run_sweep_rxdelay.sh sparse
#   ./run_sweep_rxdelay.sh sparse medium dense very_dense   # all 4
#
# Parallel:
#   ./run_sweep_rxdelay.sh sparse &
#   ./run_sweep_rxdelay.sh medium &
#   ./run_sweep_rxdelay.sh dense &
#   ./run_sweep_rxdelay.sh very_dense &
#   wait

set -euo pipefail

if [[ $# -lt 1 ]]; then
    echo "Usage: $0 <sparse|medium|dense|very_dense> [...]"
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
TIMESTAMP="$(date +%Y%m%d_%H%M%S)"

# Orchestrator
if [[ -x "$PROJECT_DIR/build-native/orchestrator/orchestrator" ]]; then
    ORCH_PATH="$PROJECT_DIR/build-native/orchestrator/orchestrator"
elif [[ -x "$PROJECT_DIR/build/orchestrator/orchestrator" ]]; then
    ORCH_PATH="$PROJECT_DIR/build/orchestrator/orchestrator"
else
    echo "ERROR: orchestrator not found"
    exit 1
fi

for VARIANT in "$@"; do
    TEST_FILE="$SCRIPT_DIR/${VARIANT}_test.json"
    CSV_FILE="$SCRIPT_DIR/results_rx_${VARIANT}_${TIMESTAMP}.csv"

    if [[ ! -f "$TEST_FILE" ]]; then
        echo "ERROR: $TEST_FILE not found — run run_sweep.sh $VARIANT first to generate topology"
        exit 1
    fi

    echo "=== RX sweep: ${VARIANT^^} ==="
    echo "  Reusing: $TEST_FILE"
    echo "  Output:  $CSV_FILE"
    echo ""

    # Fix tx/dtx at winning config. Vary rx_base only.
    # rx_delay semantics: delay = (rx_base^(0.85-score) - 1) * airtime  [score-based RX queueing]
    #   rx_base = 0   -> disabled (current setting, firmware default)
    #   rx_base = 2   -> mild prioritization
    #   rx_base = 5   -> moderate prioritization
    #   rx_base = 10  -> aggressive (old firmware default)
    #   rx_base = 20  -> very aggressive (upper clamp in firmware)
    #
    # Also test a small neighbor-count slope to see if adaptation helps.

    python3 "$SCRIPT_DIR/run_sweep.py" "$TEST_FILE" \
        --tx-base  "1.8" \
        --tx-slope "0.2" \
        --tx-pow   "1.9" \
        --dtx-base "1.1" \
        --dtx-slope "0.4" \
        --dtx-pow  "1.5" \
        --rx-base  "0:20:5" \
        --rx-slope "0:0.4:0.2" \
        --rx-pow   "1.0" \
        --clamp-max 15.0 \
        --seeds 6 \
        --orchestrator "$ORCH_PATH" \
        -j 6 \
        -o "$CSV_FILE"

    echo ""
    echo "=== Done: ${VARIANT^^}  ->  $CSV_FILE ==="
    echo ""
done
